version: "3.8"

services:
  app:
    build:
      context: .
      target: test
    image: covid-api:test
    ports:
      - 8000:80
    depends_on: 
      - db      
    command: ["./wait-for-it.sh", "db:5432", "-t", "0", "--", "pytest"]
    # command: ["pytest"]
  
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    volumes:
      - ./pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./app/.env
    ports:
      - 5432:5432
