version: "3.8"

services:
  app:
    build:
      context: .
      target: loadtest
    image: covid-api:loadtest
    ports:
      - 8000:80
    depends_on: 
      - db      
    command: ["./wait-for-it.sh", "db:5432", "-t", "0", "--", "../start.sh"]
  
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    volumes:
      - ./data:/data
      - ./pgsql:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  loadtester:
      image : locustio/locust
      ports:
        - "8089:8089"
      depends_on:
        - app
      volumes:
        - ./app:/mnt/locust
      command: -f /mnt/locust/locustfile.py --host=http://app:80

volumes:
  pgdata: