version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      target: base
    image: covid-api:debug
    restart: always
    command: ["./wait-for-it.sh", "db:5432", "-t", "0", "--", "../start-reload.sh"]
    volumes:
      - ./app:/app
    ports:
      - 8000:80
    depends_on:
      - db
  
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/data
      - ./pgsql:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes: 
  pgdata: